-- Seed employer profiles
INSERT INTO profiles (user_id, role, full_name, email, company_name, industry, location, bio)
VALUES
  ('00000000-0000-0000-0000-000000000001', 'employer', 'Tech Solutions Inc', 'jobs@techsolutions.com', 'Tech Solutions Inc', 'Technology', 'San Francisco, CA', 'Leading provider of enterprise software solutions'),
  ('00000000-0000-0000-0000-000000000002', 'employer', 'Cloud Innovations Ltd', 'hr@cloudinnovations.com', 'Cloud Innovations Ltd', 'Cloud Computing', 'New York, NY', 'Pioneering cloud infrastructure and services'),
  ('00000000-0000-0000-0000-000000000003', 'employer', 'Data Analytics Pro', 'team@dataanalyticspro.com', 'Data Analytics Pro', 'Data Science', 'Boston, MA', 'Advanced analytics and business intelligence solutions');

-- Seed jobs
INSERT INTO jobs (
  employer_id,
  title,
  description,
  category,
  location,
  salary_min,
  salary_max,
  salary_currency,
  employment_type,
  industry,
  required_skills,
  experience_level,
  deadline,
  status
)
VALUES
  (
    (SELECT id FROM profiles WHERE company_name = 'Tech Solutions Inc'),
    'Senior Full Stack Developer',
    'We''re looking for an experienced Full Stack Developer to join our growing team. You''ll work on building scalable web applications using React and Node.js.\n\nResponsibilities:\n- Design and develop new features\n- Maintain and improve existing codebase\n- Collaborate with product and design teams\n- Participate in code reviews\n\nRequirements:\n- 5+ years of full stack development experience\n- Strong knowledge of React, Node.js, and databases\n- Experience with cloud platforms (AWS, GCP, or Azure)\n- Excellent communication skills',
    'Web Development',
    'San Francisco, CA',
    120000,
    160000,
    'USD',
    'full-time',
    'Technology',
    ARRAY['React', 'Node.js', 'JavaScript', 'AWS', 'PostgreSQL'],
    'senior',
    NOW() + INTERVAL '30 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Tech Solutions Inc'),
    'DevOps Engineer',
    'Join our DevOps team and help us build robust infrastructure for our cloud platform.\n\nResponsibilities:\n- Manage and maintain cloud infrastructure\n- Implement CI/CD pipelines\n- Monitor system performance and security\n- Automate deployment processes\n\nRequirements:\n- 4+ years of DevOps experience\n- Experience with Kubernetes, Docker, and cloud platforms\n- Knowledge of scripting and automation\n- Strong problem-solving skills',
    'Infrastructure',
    'San Francisco, CA',
    110000,
    150000,
    'USD',
    'full-time',
    'Technology',
    ARRAY['Kubernetes', 'Docker', 'AWS', 'CI/CD', 'Linux'],
    'mid',
    NOW() + INTERVAL '25 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Cloud Innovations Ltd'),
    'Cloud Solutions Architect',
    'Help organizations design and implement cloud solutions. You''ll be responsible for architecting scalable, secure cloud systems.\n\nResponsibilities:\n- Design cloud architectures\n- Conduct technical assessments\n- Provide recommendations for cloud migration\n- Present to clients and stakeholders\n\nRequirements:\n- 8+ years of cloud architecture experience\n- AWS or Azure certifications preferred\n- Excellent communication and leadership skills\n- Experience with enterprise clients',
    'Architecture',
    'New York, NY',
    140000,
    180000,
    'USD',
    'full-time',
    'Cloud Computing',
    ARRAY['AWS', 'Azure', 'Cloud Architecture', 'Security', 'Networking'],
    'senior',
    NOW() + INTERVAL '35 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Cloud Innovations Ltd'),
    'Python Backend Developer',
    'Build scalable backend systems using Python. You''ll work with a team of experienced developers on our core platform.\n\nResponsibilities:\n- Develop and maintain Python applications\n- Design APIs and database schemas\n- Write unit tests and documentation\n- Participate in architectural discussions\n\nRequirements:\n- 3+ years of Python development experience\n- Knowledge of FastAPI or Django\n- Experience with relational databases\n- Version control and testing experience',
    'Backend Development',
    'New York, NY',
    100000,
    140000,
    'USD',
    'full-time',
    'Technology',
    ARRAY['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Git'],
    'mid',
    NOW() + INTERVAL '28 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Data Analytics Pro'),
    'Data Engineer',
    'Design and build data pipelines to process large-scale datasets. You''ll work with our analytics team to enable data-driven insights.\n\nResponsibilities:\n- Build and maintain data pipelines\n- Optimize database queries\n- Implement data validation and quality checks\n- Collaborate with data scientists and analysts\n\nRequirements:\n- 5+ years of data engineering experience\n- Proficiency in Python and SQL\n- Experience with big data tools (Spark, Hadoop)\n- Strong understanding of data warehousing',
    'Data Engineering',
    'Boston, MA',
    115000,
    155000,
    'USD',
    'full-time',
    'Data Science',
    ARRAY['Python', 'SQL', 'Apache Spark', 'Data Warehousing', 'ETL'],
    'senior',
    NOW() + INTERVAL '32 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Data Analytics Pro'),
    'Machine Learning Engineer',
    'Develop and deploy machine learning models that power our analytics platform.\n\nResponsibilities:\n- Build and train ML models\n- Implement model serving and monitoring\n- Conduct experiments and A/B testing\n- Optimize model performance\n\nRequirements:\n- 3+ years of ML engineering experience\n- Strong Python and statistics knowledge\n- Experience with TensorFlow or PyTorch\n- Knowledge of production ML systems',
    'Machine Learning',
    'Boston, MA',
    120000,
    160000,
    'USD',
    'full-time',
    'Data Science',
    ARRAY['Python', 'Machine Learning', 'TensorFlow', 'Statistics', 'SQL'],
    'mid',
    NOW() + INTERVAL '30 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Tech Solutions Inc'),
    'Frontend Developer',
    'Create beautiful and responsive user interfaces for our web platform.\n\nResponsibilities:\n- Build UI components\n- Optimize frontend performance\n- Work with design team\n- Ensure cross-browser compatibility\n\nRequirements:\n- 2+ years of frontend development experience\n- Proficiency in React and TypeScript\n- Knowledge of CSS and responsive design\n- Experience with state management libraries',
    'Web Development',
    'San Francisco, CA',
    90000,
    130000,
    'USD',
    'full-time',
    'Technology',
    ARRAY['React', 'TypeScript', 'CSS', 'JavaScript', 'Redux'],
    'entry',
    NOW() + INTERVAL '22 days',
    'active'
  ),
  (
    (SELECT id FROM profiles WHERE company_name = 'Cloud Innovations Ltd'),
    'Solutions Consultant',
    'Work with clients to understand their business needs and recommend cloud solutions.\n\nResponsibilities:\n- Meet with clients to understand requirements\n- Prepare technical proposals\n- Conduct training sessions\n- Provide ongoing support\n\nRequirements:\n- 4+ years of IT consulting experience\n- Strong client-facing skills\n- Cloud platform knowledge\n- Excellent presentation abilities',
    'Consulting',
    'New York, NY',
    95000,
    135000,
    'USD',
    'full-time',
    'Technology',
    ARRAY['Consulting', 'AWS', 'Communication', 'Problem Solving', 'Project Management'],
    'mid',
    NOW() + INTERVAL '27 days',
    'active'
  );
